# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with an official Python image with a version >= 3.10
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project to the container
COPY . .

# Install the package in development mode
RUN pip install -e .

# Set environment variables if needed. Adjust paths to point to default container locations.
ENV MCP_MEMORY_CHROMA_PATH=/app/chroma_db \
    MCP_MEMORY_BACKUPS_PATH=/app/backups \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

# Create necessary directories for ChromaDB and backups
RUN mkdir -p /app/chroma_db /app/backups

# Configure stdio for MCP communication
RUN chmod a+rw /dev/stdin /dev/stdout /dev/stderr

# Specify the command to run the server with stdio handling
ENTRYPOINT ["python", "-u", "-m", "mcp_memory_service.server"]